# Generated by Django 5.1.6 on 2025-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Elevé')], default='moyen', max_length=20),
        ),
    ]
